mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Apps included
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:post_id>/vote/", views.vote, name="vote"),
    path("<int:post_id>/edit_message/", views.edit_message, name="edit_message"),
    path(
        "<int:pk>/view_message/", views.PostMessageView.as_view(), name="view_message",
    ),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Post(models.Model):
    post_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    post_message = models.TextField(default="this is an empty post body")

    def __str__(self):
        return self.post_text

    def was_published_recently(self):
        return (
            self.pub_date >= timezone.now() - datetime.timedelta(days=1)
            and self.pub_date <= timezone.now()
        )


class Choice(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


"""
To clear the DB
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
"""

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Post


# generic django views:


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_post_list"

    def get_queryset(self):
        """Return the last five published posts."""
        return Post.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]


class DetailView(generic.DetailView):
    model = Post
    template_name = "polls/details.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Post.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Post
    template_name = "polls/results.html"


class PostMessageView(generic.DetailView):
    model = Post
    template_name = "polls/postmessage.html"


def vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:
        selected_post = post.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/details.html",
            {"post": post, "error_message": "You didnt select any choice"},
        )
    else:
        selected_post.votes += 1
        post.post_message = request.POST["post_message"]
        selected_post.save()
        post.save()
        return HttpResponseRedirect(reverse("polls:results", args=[post_id]))


def edit_message(request, post_id):
    print(request)
    try:
        post = get_object_or_404(Post, pk=post_id)
    except (KeyError, Post.DoesNotExist):
        return render(
            request,
            "polls/postmessage.html",
            {"post": post, "error_message": "You didnt fill any text"},
        )
    else:
        post.post_message = request.POST["post_message"]
        post.save()
        return HttpResponseRedirect(reverse("polls:results", args=[post_id]))

mysite/polls/templates/polls/details.html
<title>Post details for: Post {{post.id}} </title>

<h1>{{ post.post_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' post.id %}" method="post">
{% csrf_token %}
{% for choice in post.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
    {% comment %} <input type="text" name="post_message" id="post_message{{forloop.counter}}" value="" placeholder="write your post here"> {% endcomment %}
<input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}">Go back to latest posts</a>
</br>
<a href="{% url 'polls:view_message' post.id %}"> Edit post</a>

mysite/polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>
        myproject polls webApp
    </title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">


</head>

<body id="bg" style="background-image: url('{% static "images/background.jpeg"%}')";>
    <p>Latest posts:</p>
    {% if latest_post_list %}
    <ul>
        {% for post in latest_post_list %}
        <li><a href="{% url 'polls:detail' post.id %}">{{ post.post_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No posts are available.</p>
    {% endif %}
</body>

</html>

mysite/polls/templates/polls/postmessage.html
<title>Post message details for: Post {{post.id}} </title>

<h1>{{ post.post_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:edit_message' post.id %}" method="post">
{% csrf_token %}
    <input type="text" name="post_message" value="" placeholder="write your post here">
<input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}">Go back to latest posts</a>

mysite/polls/templates/polls/results.html
<h1>{{ post.post_text }}</h1>

<ul>
{% for choice in post.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' post.id %}">Vote again?</a>